### ISSUE TITLE
How do I get in touch with you? 

### ISSUE THREAD

**Issue by perdakovich** [gniftygnome/ductwork#2]
All emails are dead, discord is dead, all websites are dead or not working properly. there's only web archives available...

first I tried to email you - nah, gnomecraft.net email system is dead.
```
<[gnifty@gnomecraft.net](mailto:gnifty@gnomecraft.net)>: host mx2.lunixsys.com[199.58.103.135] said: 554 5.7.1
    <[gnifty@gnomecraft.net](mailto:gnifty@gnomecraft.net)>: Relay access denied (in reply to RCPT TO command)
```

well, discord isn't dead, but you're not online and you're not accepting my friend request.

Sorry for sending it there, I just don't see any other place to do it.

**Comment by gniftygnome** [comment]
Yeah, I'm not very sociable.  I deal with way too much spam and unsolicited sales attempts in a work context so things like a friend request from somebody with no channels in common on Discord is never going to get a response.  I am often online but I use the web client and Discord marks web client users as offline 24x7 (which is actually kind of nice for me).  If you remind me of your Discord handle I can try and add you, but I'm not very chatty about anything which doesn't specifically pertain to one of the Minecraft mods I maintain.

FWIW something might be wrong with your mail system, since it should be trying my other two MXes first and they should have accepted the mail.  But I seem to have forgotten the config for that domain on the fallback MX, which is fixed now.  However, if your mailer prefers my mx2 over the higher-rated MXes when those MXes are up, you'll go straight to my spam mailbox anyway.
